-- Core query: admin catalogue page, first page, newest books first.
-- This is the SQL shape generated by BookService.listAllBooks(..., status=ON_SALE).
-- Run against the same dataset before applying V5__add_book_admin_list_index.sql.
EXPLAIN ANALYZE
SELECT id, isbn, title, publisher_id, original_price, sale_price,
       stock, publish_date, edition, pages, cover_url, status,
       sales_count, create_time, update_time
FROM book
WHERE status = 'ON_SALE'
ORDER BY id DESC
LIMIT 20 OFFSET 0;
